zvireci_trhovisko/Models/Uzivatel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace zvireci_trhovisko.Models
{
    public class Uzivatel
    {
        [Key]
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole nesmí být prázdné.")]
        [StringLength(32, ErrorMessage = "Uživatelské jméno nesmí být delší než 32 znaků.")]
        [Display(Name = "Uživatelské jméno")]
        public string Uzivatelske_jmeno { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole nesmí být prázdné.")]
        [StringLength(32, ErrorMessage = "Heslo nesmí být delší než 32 znaků", MinimumLength = 3)]
        public string Heslo { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Pole nesmí být prázdné.")]
        [StringLength(32, ErrorMessage = "Email nesmí být delší než 32 znaků a kratší než 5 znaků.", MinimumLength = 5)]
        public string Email { get; set; }

        public DateTime Datum_registrace { get; set; }

    }
}

zvireci_trhovisko/Controllers/UzivatelController.cs
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace zvireci_trhovisko.Controllers
{

    public class UzivatelController : Controller
    {

        string conString = System.Configuration.ConfigurationManager.ConnectionStrings["orcl"].ConnectionString;


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PrihlasitSe()
        {
            return View("PrihlasitSe");
        }

        public ActionResult RegistrovatSe()
        {
            return View("RegistrovatSe");
        }

        public ActionResult Prihlasit_se_form(Models.Uzivatel uzivatel)
        {
            string sql = $"SELECT * FROM uzivatel WHERE uzivatelske_jmeno = '{uzivatel.Uzivatelske_jmeno}' AND heslo = '{uzivatel.Heslo}'";

            using (OracleConnection connection = new OracleConnection())
            {
                connection.ConnectionString = conString;
                connection.Open();

                OracleCommand command = new OracleCommand(sql, connection);

                using (OracleDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        try
                        {
                            int i = reader.GetInt32(0);
                            return View("Profil", uzivatel);
                        }
                        catch
                        {
                            return View("Chyba");
                        }
                    }

                    ViewBag.Zprava = "Nesprávné uživatelské jméno nebo heslo.";
                    return View("PrihlasitSe");
                }
            }
        }

        public ActionResult Registrovat_se_form(Models.Uzivatel uzivatel)
        {

            string sql = $"INSERT INTO uzivatel (id, uzivatelske_jmeno, heslo, email, datum_registrace)" +
                         $"VALUES (uzivatel_sequence.NextVal, '{uzivatel.Uzivatelske_jmeno}', '{uzivatel.Heslo}', '{uzivatel.Email}', sysdate)";


            try
            {
                using (OracleConnection connection = new OracleConnection(conString))
                {
                    connection.Open();

                    using (OracleCommand command = new OracleCommand(sql, connection))
                    {
                        command.CommandText = sql;

                        command.ExecuteNonQuery();

                        connection.Close();
                        connection.Dispose();
                    }
                }

                return View("Profil", uzivatel);
            }
            catch
            {
                return View("Chyba");
            }

            
        }

    }
}

zvireci_trhovisko/Controllers/ZvireController.cs
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using zvireci_trhovisko.Models;
using System.Windows.Forms;
using System.Drawing;

namespace zvireci_trhovisko.Controllers
{
    public class ZvireController : Controller
    {

        string conString = System.Configuration.ConfigurationManager.ConnectionStrings["orcl"].ConnectionString;



        public ActionResult Index()
        {
            var listZvirat = new List<Models.Zvire>();

            string sql = "SELECT * FROM zvire";


            using (OracleConnection connection = new OracleConnection())
            {
                connection.ConnectionString = conString;
                connection.Open();

                OracleCommand command = new OracleCommand(sql, connection);

                using (OracleDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        
                        Zvire zvire = new Zvire();
                        zvire.Id = reader.GetInt32(0);
                        zvire.Id_chovatel = reader.GetInt32(1);
                        zvire.Id_rozmer = reader.GetInt32(2);
                        zvire.Id_druh_zvirete = reader.GetInt32(3);
                        zvire.Id_obrazek = reader.GetInt32(4);
                        zvire.Nazev = reader.GetString(5);
                        zvire.Cena = reader.GetInt32(6);
                        if (reader.GetString(7) != null)
                        {
                            zvire.Popis = reader.GetString(7);
                        }
                        zvire.Datum_pridani = reader.GetDateTime(8);

                        listZvirat.Add(zvire);
                        
                    }
                }

                connection.Close();
                connection.Dispose();
            }

            return View(listZvirat);

        }

        public ActionResult VytvoritInzerat()
        {
            Zvire zvire = new Zvire();
            Obrazek obrazek = new Obrazek();
            ZvireObrazek zvireObrazek = new ZvireObrazek();
            zvireObrazek.Zvire = zvire;
            zvireObrazek.Obrazek = obrazek;

            return View("VytvoritInzerat", zvireObrazek);
        }

        public ActionResult VytvoritInzerat_form(Models.ZvireObrazek zvireObrazek)
        {


            /*
            using (MemoryStream memoryStream = new MemoryStream())
            {
                zvireObrazek.Obrazek.InputStream.CopyTo(memoryStream);
            }
            */


            string sql = $"INSERT INTO obrazek (id, datum_nahrani, datum_modifikace, obrazek)" +
                    $"VALUES (obrazekSequence.NextVal, sysdate, sysdate, '{zvireObrazek.Obrazek.Obrazek_soubor}')";

            using (OracleConnection connection = new OracleConnection(conString))
            {
                connection.Open();

                using (OracleCommand command = new OracleCommand(sql, connection))
                {
                    command.CommandText = sql;

                    command.ExecuteNonQuery();

                    connection.Close();
                    connection.Dispose();
                }
            }

            return View("Inzerat");

        }
/*
        public ActionResult FileInputObrazek()
        {

            Obrazek obrazek = new Obrazek();

            try
            {
                OpenFileDialog fileDialog = new OpenFileDialog();
                fileDialog.Filter = "Image files | *.jpg, *.png, *.bmp";
                if (fileDialog.ShowDialog() == DialogResult.OK)
                {
                    String nazevSouboru = fileDialog.FileName;
                    obrazek.Obrazek_soubor = Image.FromFile(fileDialog.FileName);

                    /*

                    var virtualPath = string.Format("~/images/{0}.jpg", nazevSouboru);

                    if (System.IO.File.Exists(Server.MapPath(virtualPath)))
                    {
                        ViewBag.obrazek = VirtualPathUtility.ToAbsolute(virtualPath);
                    }
                    *


                    string sql = $"INSERT INTO uzivatel (id, uzivatelske_jmeno, heslo, email, datum_registrace)" +
                                 $"VALUES (obrazekSequence.NextVal, sysdate, sysdate, '{obrazek}', sysdate)";

                    using (OracleConnection connection = new OracleConnection(conString))
                    {
                        connection.Open();

                        using (OracleCommand command = new OracleCommand(sql, connection))
                        {
                            command.CommandText = sql;

                            command.ExecuteNonQuery();

                            connection.Close();
                            connection.Dispose();
                        }
                    }

                    return View("VytvoritInzerat");

                }
                else
                {
                    return View("Chyba");
                }

            }
            catch (Exception ex)
            {
                return View("Chyba");
            }

    
        }
        */
    }
}

zvireci_trhovisko/Views/Uzivatel/Chyba.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chyba</h2>
<p>Něco se nepodařilo.</p>

zvireci_trhovisko/Views/Uzivatel/PrihlasitSe.cshtml
@model zvireci_trhovisko.Models.Uzivatel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Přihlásit se</h2>

@using (Html.BeginForm("Prihlasit_se_form", "Uzivatel", FormMethod.Post))
{
    <div>
        <h5 style="color:red">@ViewBag.Zprava</h5>
    </div>
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Uzivatelske_jmeno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uzivatelske_jmeno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uzivatelske_jmeno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Heslo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Heslo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Heslo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Přihlásit se" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zpět", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

zvireci_trhovisko/Views/Uzivatel/Profil.cshtml
@model zvireci_trhovisko.Models.Uzivatel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Profil</h2>

<p>
    @Model.Uzivatelske_jmeno
    @Model.Heslo
    @Model.Email

    @Html.ActionLink("Vytvořit inzerát", "VytvoritInzerat", "Zvire")
</p>

zvireci_trhovisko/Views/Uzivatel/RegistrovatSe.cshtml
@model zvireci_trhovisko.Models.Uzivatel


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrovat se</h2>


@using (Html.BeginForm("Registrovat_se_form", "Uzivatel", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Uzivatelske_jmeno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uzivatelske_jmeno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uzivatelske_jmeno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Heslo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Heslo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Heslo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrovat se" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zpět", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}